---
title: "Final-Project-Quiz1"
author: "Seshadri K"
date: "6/25/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Just for fun, the questions in this quiz will be solved using shell commands. 

### 1. The ğšğš—_ğš„ğš‚.ğš‹ğš•ğš˜ğšğšœ.ğšğš¡ğš  file is how many megabytes?
Answer: 200 MB

### 2. The ğšğš—_ğš„ğš‚.ğšğš ğš’ğšğšğšğš›.ğšğš¡ğš has how many lines of text?
 
 ```{bash}
wc -l ./Coursera-SwiftKey/en_US/en_US.twitter.txt 
```
The correct answer is over 2 million lines. 

### 3. What is the length of the longest line seen in any of the three en_US data sets?
```{bash}
for file in ./Coursera-SwiftKey/en_US/en_US.*.txt; do echo $file; cat $file|awk '{print length, $0}'|sort -nr|head -1 |wc; done
```

So, the answer is "Over 40 thousand in the blogs data set"

### 4. In the en_US twitter data set, if you divide the number of lines where the word "love" (all lowercase) occurs by the number of lines the word "hate" (all lowercase) occurs, about what do you get?

```{bash}
love=$(grep "love" ./Coursera-SwiftKey/en_US/en_US.twitter.txt | wc -l ); 
hate=$(grep "hate" ./Coursera-SwiftKey/en_US/en_US.twitter.txt | wc -l); 
echo $love/$hate | bc -l
```

The answer is 4. 

### 5. The one tweet in the en_US twitter data set that matches the word "biostats" says what?

```{bash}

grep "biostats" ./Coursera-SwiftKey/en_US/en_US.twitter.txt 

```

It says that they haven't studied for the biostats exam. 

### 6. How many tweets have the exact characters "A computer once beat me at chess, but it was no match for me at kickboxing". (I.e. the line matches those characters exactly.)

```{bash}
grep "A computer once beat me at chess, but it was no match for me at kickboxing" ./Coursera-SwiftKey/en_US/en_US.twitter.txt  |wc -l
```

The answer is 3. 